version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis01
    ports:
      - target: 6379
        host_ip: 127.0.0.1
        published: 6379
        protocol: tcp
        mode: host
    restart: always
    expose:
      - '6379'
    volumes:
      - .:/data

  web:
    image: todo_api_django
    container_name: django_server
    build: .
    volumes:
      - .:/todoapi
    environment:
        DEBUG: 'true'
    ports:
      - target: 8000
        host_ip: 127.0.0.1
        published: 8000
        protocol: tcp
        mode: host
    links:
      - redis
    depends_on:
      - redis
